"""initial_schema

Revision ID: 2158f2d70ea1
Revises: 
Create Date: 2026-05-05 17:56:26.835680
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '2158f2d70ea1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updatedBy', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_settings'))
    )
    op.create_index(op.f('ix_admin_settings_key'), 'admin_settings', ['key'], unique=True)
    op.create_index(op.f('ix_admin_settings_namespace'), 'admin_settings', ['namespace'], unique=False)
    op.create_table('colleges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shortName', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_colleges'))
    )
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('urgencyLevel', sa.Integer(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions'))
    )
    op.create_index(op.f('ix_positions_title'), 'positions', ['title'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contactEmail', sa.String(length=255), nullable=False),
    sa.Column('contactPhone', sa.String(length=30), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors')),
    sa.UniqueConstraint('contactEmail', name=op.f('uq_vendors_contactEmail'))
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateCode', sa.String(length=64), nullable=False),
    sa.Column('fullName', sa.String(length=255), nullable=False),
    sa.Column('personalEmail', sa.String(length=255), nullable=False),
    sa.Column('etharaEmail', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('aadhaarLast4', sa.String(length=4), nullable=True),
    sa.Column('dateOfBirth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('maritalStatus', sa.String(length=30), nullable=True),
    sa.Column('experienceType', sa.String(length=50), nullable=True),
    sa.Column('currentCompany', sa.String(length=255), nullable=True),
    sa.Column('currentCTC', sa.Float(), nullable=True),
    sa.Column('expectedCTC', sa.Float(), nullable=True),
    sa.Column('noticePeriod', sa.Integer(), nullable=True),
    sa.Column('sourceType', sa.Enum('vendor', 'internal_hiring', 'lateral_hiring', 'employee_referral', 'direct_application', name='source_type', native_enum=False), nullable=False),
    sa.Column('sourceId', sa.String(length=32), nullable=True),
    sa.Column('positionId', sa.String(length=32), nullable=False),
    sa.Column('collegeId', sa.String(length=32), nullable=True),
    sa.Column('vendorId', sa.String(length=32), nullable=True),
    sa.Column('currentStage', sa.Enum('new_application', 'source_tagged', 'resume_uploaded', 'resume_screening_pending', 'resume_shortlisted', 'resume_rejected', 'evaluation_assigned', 'evaluation_in_progress', 'evaluation_passed', 'evaluation_failed', 'selection_form_sent', 'selection_form_submitted', 'selection_form_validated', 'contract_sent', 'contract_signed', 'induction_completed', 'it_email_created', 'welcome_mail_sent', 'statutory_forms_sent', 'statutory_forms_submitted', 'compliance_verified', 'onboarding_completed', name='candidate_stage', native_enum=False), nullable=False),
    sa.Column('currentStatus', sa.String(length=255), nullable=False),
    sa.Column('priorityScore', sa.Integer(), nullable=False),
    sa.Column('isDuplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicateReason', sa.Text(), nullable=True),
    sa.Column('isReapplicationBlocked', sa.Boolean(), nullable=False),
    sa.Column('lastAppliedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumeUrl', sa.String(length=500), nullable=True),
    sa.Column('resumeScore', sa.Float(), nullable=True),
    sa.Column('resumeSummary', sa.Text(), nullable=True),
    sa.Column('screening_payload', sa.JSON(), nullable=True),
    sa.Column('llm_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collegeId'], ['colleges.id'], name=op.f('fk_candidates_collegeId_colleges')),
    sa.ForeignKeyConstraint(['positionId'], ['positions.id'], name=op.f('fk_candidates_positionId_positions')),
    sa.ForeignKeyConstraint(['vendorId'], ['vendors.id'], name=op.f('fk_candidates_vendorId_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates'))
    )
    op.create_index(op.f('ix_candidates_candidateCode'), 'candidates', ['candidateCode'], unique=True)
    op.create_index(op.f('ix_candidates_currentStage'), 'candidates', ['currentStage'], unique=False)
    op.create_index(op.f('ix_candidates_fullName'), 'candidates', ['fullName'], unique=False)
    op.create_index(op.f('ix_candidates_personalEmail'), 'candidates', ['personalEmail'], unique=False)
    op.create_index(op.f('ix_candidates_sourceType'), 'candidates', ['sourceType'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'hr', 'vendor', 'employee_referrer', 'evaluator', 'it_team', 'candidate', name='role', native_enum=False), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('lastLoginAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refreshToken', sa.String(length=255), nullable=True),
    sa.Column('permission_overrides', sa.JSON(), nullable=False),
    sa.Column('vendor_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_users_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('entityType', sa.String(length=100), nullable=False),
    sa.Column('entityId', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('performedBy', sa.String(length=32), nullable=False),
    sa.Column('performedByName', sa.String(length=255), nullable=True),
    sa.Column('performedByRole', sa.String(length=100), nullable=True),
    sa.Column('candidateId', sa.String(length=32), nullable=True),
    sa.Column('userId', sa.String(length=32), nullable=True),
    sa.Column('ipAddress', sa.String(length=100), nullable=True),
    sa.Column('userAgent', sa.String(length=255), nullable=True),
    sa.Column('oldValue', sa.JSON(), nullable=True),
    sa.Column('newValue', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_audit_logs_candidateId_candidates')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('fk_audit_logs_userId_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_entityType'), 'audit_logs', ['entityType'], unique=False)
    op.create_table('compliance_forms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('formType', sa.String(length=50), nullable=False),
    sa.Column('formTitle', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('formData', sa.JSON(), nullable=True),
    sa.Column('submittedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verifiedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_compliance_forms_candidateId_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_forms'))
    )
    op.create_table('contracts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'viewed', 'signed', 'expired', name='contract_status', native_enum=False), nullable=False),
    sa.Column('documensoId', sa.String(length=255), nullable=True),
    sa.Column('signedUrl', sa.String(length=500), nullable=True),
    sa.Column('sentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiresAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ctc', sa.Float(), nullable=True),
    sa.Column('joiningDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_contracts_candidateId_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contracts')),
    sa.UniqueConstraint('candidateId', name=op.f('uq_contracts_candidateId'))
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('fileName', sa.String(length=255), nullable=False),
    sa.Column('fileUrl', sa.String(length=500), nullable=False),
    sa.Column('fileSize', sa.Integer(), nullable=True),
    sa.Column('mimeType', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('verifiedBy', sa.String(length=32), nullable=True),
    sa.Column('verifiedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_status', sa.String(length=50), nullable=False),
    sa.Column('ocr_provider', sa.String(length=50), nullable=True),
    sa.Column('extracted_data', sa.JSON(), nullable=True),
    sa.Column('llm_extracted_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_documents_candidateId_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_type'), 'documents', ['type'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('responsibleUserId', sa.String(length=32), nullable=False),
    sa.Column('slaDeadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delayedBy', sa.String(length=100), nullable=False),
    sa.Column('escalationLevel', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'acknowledged', 'resolved', name='escalation_status', native_enum=False), nullable=False),
    sa.Column('emailSentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolvedBy', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_escalations_candidateId_candidates')),
    sa.ForeignKeyConstraint(['responsibleUserId'], ['users.id'], name=op.f('fk_escalations_responsibleUserId_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalations'))
    )
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('evaluatorId', sa.String(length=32), nullable=False),
    sa.Column('technicalSkills', sa.Integer(), nullable=True),
    sa.Column('communication', sa.Integer(), nullable=True),
    sa.Column('problemSolving', sa.Integer(), nullable=True),
    sa.Column('culturalFit', sa.Integer(), nullable=True),
    sa.Column('attitude', sa.Integer(), nullable=True),
    sa.Column('totalScore', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_evaluations_candidateId_candidates')),
    sa.ForeignKeyConstraint(['evaluatorId'], ['users.id'], name=op.f('fk_evaluations_evaluatorId_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_table('it_requests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('requestedBy', sa.String(length=32), nullable=False),
    sa.Column('assignedToId', sa.String(length=32), nullable=True),
    sa.Column('suggestedEmail', sa.String(length=255), nullable=False),
    sa.Column('createdEmail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('completedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignedToId'], ['users.id'], name=op.f('fk_it_requests_assignedToId_users')),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_it_requests_candidateId_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_it_requests')),
    sa.UniqueConstraint('candidateId', name=op.f('uq_it_requests_candidateId'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('userId', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('info', 'warning', 'success', 'error', 'action', name='notification_type', native_enum=False), nullable=False),
    sa.Column('isRead', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_notifications_candidateId_candidates')),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name=op.f('fk_notifications_userId_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_table('selection_forms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('sentAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submittedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validatedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('formData', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_selection_forms_candidateId_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_selection_forms')),
    sa.UniqueConstraint('candidateId', name=op.f('uq_selection_forms_candidateId'))
    )
    op.create_table('stage_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('candidateId', sa.String(length=32), nullable=False),
    sa.Column('fromStage', sa.Enum('new_application', 'source_tagged', 'resume_uploaded', 'resume_screening_pending', 'resume_shortlisted', 'resume_rejected', 'evaluation_assigned', 'evaluation_in_progress', 'evaluation_passed', 'evaluation_failed', 'selection_form_sent', 'selection_form_submitted', 'selection_form_validated', 'contract_sent', 'contract_signed', 'induction_completed', 'it_email_created', 'welcome_mail_sent', 'statutory_forms_sent', 'statutory_forms_submitted', 'compliance_verified', 'onboarding_completed', name='candidate_stage', native_enum=False), nullable=False),
    sa.Column('toStage', sa.Enum('new_application', 'source_tagged', 'resume_uploaded', 'resume_screening_pending', 'resume_shortlisted', 'resume_rejected', 'evaluation_assigned', 'evaluation_in_progress', 'evaluation_passed', 'evaluation_failed', 'selection_form_sent', 'selection_form_submitted', 'selection_form_validated', 'contract_sent', 'contract_signed', 'induction_completed', 'it_email_created', 'welcome_mail_sent', 'statutory_forms_sent', 'statutory_forms_submitted', 'compliance_verified', 'onboarding_completed', name='candidate_stage', native_enum=False), nullable=False),
    sa.Column('changedBy', sa.String(length=32), nullable=False),
    sa.Column('changedByName', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidateId'], ['candidates.id'], name=op.f('fk_stage_logs_candidateId_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_logs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_logs')
    op.drop_table('selection_forms')
    op.drop_table('notifications')
    op.drop_table('it_requests')
    op.drop_table('evaluations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_documents_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('contracts')
    op.drop_table('compliance_forms')
    op.drop_index(op.f('ix_audit_logs_entityType'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_candidates_sourceType'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_personalEmail'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_fullName'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_currentStage'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_candidateCode'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_positions_title'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_table('colleges')
    op.drop_index(op.f('ix_admin_settings_namespace'), table_name='admin_settings')
    op.drop_index(op.f('ix_admin_settings_key'), table_name='admin_settings')
    op.drop_table('admin_settings')
    # ### end Alembic commands ###

