"""add_assessment_templates

Revision ID: 41fd8cc2f7e7
Revises: 7b4e2d1c9a6f
Create Date: 2026-05-29 14:19:01.548320
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '41fd8cc2f7e7'
down_revision: str | None = '7b4e2d1c9a6f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.String(length=32), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdBy', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], name=op.f('fk_assessment_templates_createdBy_users')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_assessment_templates_position_id_positions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_templates'))
    )
    op.create_index(op.f('ix_assessment_templates_position_id'), 'assessment_templates', ['position_id'], unique=False)
    op.create_index(op.f('ix_assessment_templates_title'), 'assessment_templates', ['title'], unique=False)
    op.add_column('candidate_assessments', sa.Column('templateId', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_candidate_assessments_templateId'), 'candidate_assessments', ['templateId'], unique=False)
    op.create_foreign_key(op.f('fk_candidate_assessments_templateId_assessment_templates'), 'candidate_assessments', 'assessment_templates', ['templateId'], ['id'])
    op.drop_constraint(op.f('uq_candidate_id_card_forms_candidateId'), 'candidate_id_card_forms', type_='unique')
    op.drop_index(op.f('ix_candidate_id_card_forms_candidateId'), table_name='candidate_id_card_forms')
    op.create_index(op.f('ix_candidate_id_card_forms_candidateId'), 'candidate_id_card_forms', ['candidateId'], unique=True)
    op.drop_constraint(op.f('fk_documenso_contract_fields_candidateId_candidates'), 'documenso_contract_fields', type_='foreignkey')
    op.drop_constraint(op.f('fk_documenso_contract_fields_contractId_contracts'), 'documenso_contract_fields', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documenso_contract_fields_candidateId_candidates'), 'documenso_contract_fields', 'candidates', ['candidateId'], ['id'])
    op.create_foreign_key(op.f('fk_documenso_contract_fields_contractId_contracts'), 'documenso_contract_fields', 'contracts', ['contractId'], ['id'])
    op.drop_constraint(op.f('fk_documenso_signed_profiles_candidateId_candidates'), 'documenso_signed_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documenso_signed_profiles_candidateId_candidates'), 'documenso_signed_profiles', 'candidates', ['candidateId'], ['id'])
    op.drop_constraint(op.f('fk_documenso_sync_logs_candidateId_candidates'), 'documenso_sync_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documenso_sync_logs_candidateId_candidates'), 'documenso_sync_logs', 'candidates', ['candidateId'], ['id'])
    op.drop_constraint(op.f('uq_employee_profiles_employeeCode'), 'employee_profiles', type_='unique')
    op.drop_constraint(op.f('uq_employee_profiles_etharaEmail'), 'employee_profiles', type_='unique')
    op.drop_index(op.f('ix_employee_profiles_employeeCode'), table_name='employee_profiles')
    op.create_index(op.f('ix_employee_profiles_employeeCode'), 'employee_profiles', ['employeeCode'], unique=True)
    op.drop_index(op.f('ix_employee_profiles_etharaEmail'), table_name='employee_profiles')
    op.create_index(op.f('ix_employee_profiles_etharaEmail'), 'employee_profiles', ['etharaEmail'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_profiles_etharaEmail'), table_name='employee_profiles')
    op.create_index(op.f('ix_employee_profiles_etharaEmail'), 'employee_profiles', ['etharaEmail'], unique=False)
    op.drop_index(op.f('ix_employee_profiles_employeeCode'), table_name='employee_profiles')
    op.create_index(op.f('ix_employee_profiles_employeeCode'), 'employee_profiles', ['employeeCode'], unique=False)
    op.create_unique_constraint(op.f('uq_employee_profiles_etharaEmail'), 'employee_profiles', ['etharaEmail'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_employee_profiles_employeeCode'), 'employee_profiles', ['employeeCode'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_documenso_sync_logs_candidateId_candidates'), 'documenso_sync_logs', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documenso_sync_logs_candidateId_candidates'), 'documenso_sync_logs', 'candidates', ['candidateId'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_documenso_signed_profiles_candidateId_candidates'), 'documenso_signed_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documenso_signed_profiles_candidateId_candidates'), 'documenso_signed_profiles', 'candidates', ['candidateId'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('fk_documenso_contract_fields_contractId_contracts'), 'documenso_contract_fields', type_='foreignkey')
    op.drop_constraint(op.f('fk_documenso_contract_fields_candidateId_candidates'), 'documenso_contract_fields', type_='foreignkey')
    op.create_foreign_key(op.f('fk_documenso_contract_fields_contractId_contracts'), 'documenso_contract_fields', 'contracts', ['contractId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_documenso_contract_fields_candidateId_candidates'), 'documenso_contract_fields', 'candidates', ['candidateId'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_candidate_id_card_forms_candidateId'), table_name='candidate_id_card_forms')
    op.create_index(op.f('ix_candidate_id_card_forms_candidateId'), 'candidate_id_card_forms', ['candidateId'], unique=False)
    op.create_unique_constraint(op.f('uq_candidate_id_card_forms_candidateId'), 'candidate_id_card_forms', ['candidateId'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('fk_candidate_assessments_templateId_assessment_templates'), 'candidate_assessments', type_='foreignkey')
    op.drop_index(op.f('ix_candidate_assessments_templateId'), table_name='candidate_assessments')
    op.drop_column('candidate_assessments', 'templateId')
    op.drop_index(op.f('ix_assessment_templates_title'), table_name='assessment_templates')
    op.drop_index(op.f('ix_assessment_templates_position_id'), table_name='assessment_templates')
    op.drop_table('assessment_templates')
    # ### end Alembic commands ###

