"""add_screening_prompt_interview_fields_resume_text

Revision ID: 87f282719d49
Revises: c3b8e2f4d913
Create Date: 2026-05-11 16:52:54.427746
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '87f282719d49'
down_revision: str | None = 'c3b8e2f4d913'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('resumeText', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('resumeKeyPoints', sa.JSON(), nullable=True))
    op.add_column('candidates', sa.Column('aadhaarExtracted', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_candidates_portalUserId'), table_name='candidates')
    op.add_column('evaluations', sa.Column('interviewSubject', sa.String(length=500), nullable=True))
    op.add_column('evaluations', sa.Column('interviewScheduledAt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('evaluations', sa.Column('interviewStatus', sa.String(length=50), nullable=True))
    op.add_column('evaluations', sa.Column('interviewNotes', sa.Text(), nullable=True))
    op.add_column('positions', sa.Column('screeningPrompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'screeningPrompt')
    op.drop_column('evaluations', 'interviewNotes')
    op.drop_column('evaluations', 'interviewStatus')
    op.drop_column('evaluations', 'interviewScheduledAt')
    op.drop_column('evaluations', 'interviewSubject')
    op.create_index(op.f('ix_candidates_portalUserId'), 'candidates', ['portalUserId'], unique=False)
    op.drop_column('candidates', 'aadhaarExtracted')
    op.drop_column('candidates', 'resumeKeyPoints')
    op.drop_column('candidates', 'resumeText')
    # ### end Alembic commands ###

